<?php
/*------------------------------------------------------------------------
 # SM Deal - Version 1.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/?>
		
<script type="text/javascript">
//<![CDATA[
data = new Date(2013,10,26,12,00,00);
var listdeal = [];
function CountDown(date,id){
	dateNow = new Date();
	amount = date.getTime() - dateNow.getTime();
	delete dateNow;
	if(amount < 0){
		document.getElementById(id).innerHTML="Now!";
	} else{
		days=0;hours=0;mins=0;secs=0;out="";
		amount = Math.floor(amount/1000);
		days=Math.floor(amount/86400);
		amount=amount%86400;
		hours=Math.floor(amount/3600);
		amount=amount%3600;
		mins=Math.floor(amount/60);
		amount=amount%60;
		secs=Math.floor(amount);
		//if(days != 0){}
		out += "<div>"+days+"</div>" + "<div>"+hours+"</div>"+"<div>"+mins+"</div>"+"<div>"+secs+"</div>"; 
		//if(hours != 0){}
		out += "<div class='title'>"+((Dias==1)?"day":"Dias")+"</div>"+"<div class='title'>"+((Horas==1)?"hour":"Horas")+"</div>"+"<div class='title'>"+((Mins==1)?"min":"Mins")+"</div>"+"<div class='title'>"+((Secs==1)?"sec":"Secs")+"</div>";
		
		out = out.substr(0,out.length-2);
		document.getElementById(id).innerHTML=out;
		setTimeout(function(){CountDown(date,id)}, 1000);
	}
}
//]]>
</script>
<?php
$dayDate  = Mage::app()->getLocale()->date()->toString(Varien_Date::DATETIME_INTERNAL_FORMAT);
$deals  = Mage::getResourceModel('deal/deal_product_collection')->joinFields()->joinFieldsdeal()
				->addFilter('status', '1', "=")
				->addFilter('end_date', $dayDate, ">");

if(Mage::getStoreConfig('deal/deal/orderby') == 1){
	$deals->OrderbyAdd('start_date','desc');
}else{
	$deals->OrderbyAdd('end_date','desc');
}
		
$productBlock=$this->getLayout()->createBlock("catalog/product_list");
$check_array =$deals->getData();

/*get config backend*/
$general_setting = Mage::getStoreConfig('deal/deal');
$product_setting = Mage::getStoreConfig('deal/product_display_setting');
?>
<?php if( !empty($check_array) && $general_setting['isenabled'] == 1 ){
	$uniqued ='sm_deal_'.rand().time();
?>
<?php 
$total = count($deals->getData()); 

?>
<div id="<?php echo $uniqued;?>" class="sm-deal-wrap products-grid ">	
	<div class="block-title block-title-style">
		<span><?php echo $this->__('Deals of the day'); ?></span>
	</div>
	<div class="sm-deal-inner m-lr">
		<div class="deal-list-item">
			
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="0">	
	<div class="carousel-inner">	
			
			<?php $j = 0; foreach($deals->getData() as $product_data){ 
			$_product = Mage::getModel('catalog/product')->load($product_data['entity_id']);
			$now = date("Y-m-d H:m:s");
	        $newsFrom= $_product->getNewsFromDate();
	        $newsTo=  $_product->getNewsToDate();
	        $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
	        $special_from_date = $_product->getSpecialFromDate();
	        $special_to_date = $_product->getSpecialToDate();	
			?>
			<?php if($j%2 == 0){ ?>
			<div class="item <?php if($j==0){ echo 'active'; } ?>">
			<?php }?>
			<div class="inner-item">
				<?php                          
                    if($newsFrom != ''){                            
                    if (($now>=$newsFrom && $now<=$newsTo)||($now>=$newsFrom && $newsTo =='')){  ?>
                        <div class='new-item'></div>
                    <?php }
                    }else{
                    if(($newsTo != "") && $newsTo >= $now){ 
                    ?>
                        <div class='new-item'></div>
                    <?php }
                    }
                    if (($specialprice && ($special_from_date <= $now) && ($special_to_date >= $now || $special_to_date =="" ))){?>
                        <div class='sale-item deal'>
                        	<div class="wrap-number">
                            <span class="text_number">
                            <?php
                            $saleof= abs(($specialprice/($_product->getPrice()))*100-100);?>
                            <?php  echo '-'; print_r(floor($saleof)); ?>
                            </span>
                           <span class="percent">%</span>
                           </div> 
                        </div>
                <?php }
                ?> 
				<div class="item-wrap item-deal  <?php if($j%2 == 0) { echo 'first'; }?>">
						<div class="item-info">
							<div class="item-inner">
							<?php if( $product_setting['product_title_disp'] == 1 ){?>
							<div class="product-name">
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo substr($this->htmlEscape($_product->getName()), 0, $product_setting['product_title_max_characters']);
								
								?>
								</a>
							</div>
							<?php }?>
							<div class="item-content">
								<?php if( $product_setting['product_reviews_count'] == 1 ){?>
								
									<?php  echo $productBlock->getReviewsSummaryHtml($_product, 'short'); ?>
								
								<?php }?>
								<?php if( $product_setting['product_price_disp'] == 1 ){?>
								
								<?php if($_product->isSaleable()){
									echo $productBlock->getPriceHtml($_product, true); 
								} ?>
								
								<?php }?>
								<?php if( $product_setting['product_description_disp'] == 1 ){?>
								<div class="item-des">
									<?php echo substr($_product->getshort_description(), 0, $product_setting['product_description_max_characters']);?>
								</div>
								<?php }?>
								</div>
							</div>									
						</div>
						<div class="item-image">
							<a class="product-image"  href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">				
								<?php $_media = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages() ?>						                    
			                    <?php $count_item=0; $check_img=0;?>		                    
			                    <?php $check_img = count($_media);?>							
								
								<img class="first_image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(224,200); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> 

							</a>	
						<?php		
						$string = $this->getAddToCartUrl($_product);
						?>						
						<!--<button type="button" title="<?php //echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php //echo $_product->getProductUrl().$string; ?>')"><span><span><?php //echo $this->__('Add to Cart') ?></span></span></button>-->

							<div class="group-item">
                           		<?php if($_product->isSaleable()): ?>
                                <a title="<?php echo $this->__('Adicionar ao Carrinho') ?>" class="btn-cart" onclick="setLocation('<?php echo $_product->getProductUrl().$string; ?>')"><span></span><?php echo $this->__('Adicionar ao Carrinho') ?></a>
                                <?php else: ?>
                                    <a href="#" class="availability out-of-stock"><span></span><?php echo $this->__('Fora de Estoque') ?></a>
                                <?php endif; ?>
                            </div>							
						</div>
						<div class="item-info bottom">
							
								<div id="product_time_<?php echo $j;?>" class="product_time"></div>	
								<script type="text/javascript">
								//<![CDATA[
									listdeal.push('product_time_<?php echo $j."&&||&&".date("Y/m/d", strtotime($product_data['end_date']));?>') ;
								//]]>
								</script>		
															
						</div>
				</div> <!-- end item-deal -->
		</div><!-- end inner item-->
		<?php if($j%2 == 1){?>
		</div><!-- end item -->		
		<?php } ?>
		<?php if($total==$j && $j%2 != 1){?>
			</div>
		<?php }?>
		<?php $j++; }?>	
		
	
	</div><!-- end carousel-inner -->
	
	
	<ul class="btn-p-n">
        <li title="Previous">
            <a class="prev carousel-control" href="#carousel-example-generic" data-slide="prev"></a>
        </li>
        <li title="Next">
            <a class="next carousel-control" href="#carousel-example-generic" data-slide="next"></a>
        </li>
    </ul>
</div><!-- end carousel-example-generic -->

		</div>				
	</div>
</div>
<script type="text/javascript">
//<![CDATA[
window.onload=function(){
	if(listdeal.length > 0){
		for(i=0;i<listdeal.length;i++)
		{
			var arr = listdeal[i].split("&&||&&"); 
			var data = new Date(arr[1]);
			CountDown(data, arr[0]);
		}	
	}
};
//]]>
</script>	
<?php } ?>

