<?php
/*------------------------------------------------------------------------
 # SM Category Slider - Version 1.0.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

$list = $this->_getProducts();
$cat_info = $this->getListCategoriesFilter();

if(!empty($list)){ 
	$import_str = "";
	$jsHelper = Mage::helper('core/js');
		// jquery has not added yet
	
		$import_str .= $jsHelper->includeSkinScript('sm/categoryslider/js/categoryslider.js');
		
	echo $import_str;

	$tag_id = 'sm_categoryslider_'.rand().time();
	$helper = Mage::helper('categoryslider/data');
	$stop = (int)$this->_getConfig('stop',1) ? 'hover' : '';
	$play = (int)$this->_getConfig('play',1);
	$interval = (int)$this->_getConfig('delay');
	$interval = $play ? $interval : 0;
	$speed =(int)$this->_getConfig('duration');
	$start = (int) $this->_getConfig('start');
	$start = ( $start <= 0 || $start > count($list) ) ? 0 : $start - 1;
	$step = (int)$this->_getConfig('scroll',1);
	$step = $step <= 0 ? 1: $step;
	$effect = $this->_getConfig('effect');
	$width = $this->_getConfig('imgcfg_width');
	$height = $this->_getConfig('imgcfg_height');
?>
	<?php if($this->_getConfig('pretext') != '') { ?>
		<div class="pre-text"><?php echo $this->_getConfig('pretext'); ?></div>
	<?php } ?>

	<div id="<?php echo $tag_id; ?>" class="sm-categoryslider sm-categoryslider-preload <?php if( $this->_getConfig('cat_image_display') == 0 ){echo 'no-cat-image';}?> <?php if( $this->_getConfig('cat_sub_display') == 0 ){echo 'no-cat-sub';}?>">
			<div class="sm-categoryslider-loading"></div>
			<?php foreach( $cat_info as $cat){?>
			<div class="page-title-categoryslider block-title-style">
				<span><?php echo $cat['name'];?></span>
			</div>
			<?php }?>
			<?php if( $this->_getConfig('button_display') == 1 ){?>
			<div class="page-button">
				<ul class="control-button">
					<li class="preview">Prev</li>
					<li class="next">Next</li>
				</ul>		
			</div>
			<?php }?>
		<?php $class_respl = 'preset01-' . $this->_getConfig('nb_column1', 4) . ' preset02-' . $this->_getConfig('nb_column2', 3) . ' preset03-' . $this->_getConfig('nb_column3', 2) . ' preset04-' . $this->_getConfig('nb_column4', 2) . ' preset05-' . $this->_getConfig('nb_column5', 1); ?>
		<div class="categoryslider-content products-grid <?php echo $class_respl; ?>">
			<?php foreach( $cat_info as $cat){
				if( $this->_getConfig('cat_image_display') == 1 ){?>
				<div class="item-cat-image">
					<div class="cat-image">
						<a href="<?php echo $cat['link']; ?>" title="<?php echo $cat['name'];?>">
						<img width="<?php echo $this->_getConfig('cat_image_width', 210);?>" height="<?php echo $this->_getConfig('cat_image_height', 400);?>" src="<?php echo $cat['image'];?>" alt="<?php echo $cat['name'];?>"/>						
						</a>
					</div>
				</div>
			<?php }}?>
			<div class="categoryslider not-js cols-6">			
				<div class="vpo-wrap">
					<div class="vp">
						<div class="vpi-wrap tt-effect-<?php echo $effect;?> tt-effect-delay">						
						<?php foreach($list as $_product){


							$_product1 = Mage::getModel('catalog/product')->load($_product->getId());
							$now = date("Y-m-d H:m:s");
					        $newsFrom= $_product1->getNewsFromDate();
					        $newsTo=  $_product1->getNewsToDate();
					        $specialprice = Mage::getModel('catalog/product')->load($_product1->getId())->getSpecialPrice(); 
					        $special_from_date = $_product1->getSpecialFromDate();
					        $special_to_date = $_product1->getSpecialToDate();

						?>
							<div class="item">
								<div class="item-wrap">
									<?php                          
				                    if($newsFrom != ''){                            
				                    if (($now>=$newsFrom && $now<=$newsTo)||($now>=$newsFrom && $newsTo =='')){  ?>
				                        <div class='new-item'></div>
				                    <?php }
				                    }else{
				                    if(($newsTo != "") && $newsTo >= $now){ 
				                    ?>
				                        <div class='new-item'></div>
				                    <?php }
				                    }
				                    if (($specialprice && ($special_from_date <= $now) && ($special_to_date >= $now || $special_to_date =="" ))){?>
				                        <div class='sale-item'></div>
					                <?php }
					                ?>
								<div class="wrap-new-sale">
									
								<?php if( (int)$this->_getConfig('imgcfg_from_product_image',1) ) { ?>
									<div class="item-image item-height">										
										<a class="product-image" href="<?php echo $_product->link;?>" title="<?php echo $_product->title; ?>" <?php echo $helper->parseTarget($this->_getConfig('product_links_target'));?> >

											<img class="first_image" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize($width,$height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>" /> 
										</a>
										<div class="group-item">
										<?php if ((int)$this->_getConfig('product_addcart_display', 1)) : ?>
											<?php if($_product->isSaleable()): ?>
												<a title="<?php echo $this->__('Add to cart') ?>" class="btn-cart"  onclick="setLocation('<?php echo $this->getAddToCartUrl($_product); ?>')" ><?php echo $this->__('Add to Cart') ?></a>
											<?php else: ?>
												<a href="#" class="availability out-of-stock"><?php echo $this->__('Out of stock') ?></a>
											<?php endif; 
											endif;

										if ((int)$this->_getConfig('product_addwishlist_display', 1) || (int)$this->_getConfig('product_addcompare_display', 1)) :?>	
											<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
		                                        <a title="<?php echo $this->__('Add to compare') ?>" href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a>
		                                    <?php endif; ?>
		                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
		                                       <a title="<?php echo $this->__('Add to wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
		                                    <?php endif; ?>
										<?php endif;?>
										</div>											
									</div>
								<?php } ?>
									<div class="item-info">
										<div class="item-inner">
										<?php if( (int)$this->_getConfig('product_title_display',1) ) { ?>
											<div class="item-title product-name">
												<a href="<?php echo $_product->link;?>" title="<?php echo $_product->title; ?>" <?php echo $helper->parseTarget($this->_getConfig('product_links_target'));?> >
													<?php echo $helper->truncate($_product->title,$this->_getConfig('product_title_maxlength'),'');?>
												</a>
											</div>
										<?php } ?>
											<div class="item-content">
											<?php 
											if((int)$this->_getConfig('product_description_display',1) && $helper->_trimEncode($_product->_description) != '' ){?>
												<div class="item-des">
													<?php echo $_product->_description; ?>
												</div>
											<?php }?>
												<?php if((int)$this->_getConfig('product_reviews_count',1)){ ?>
												<div class="item-review">
													<?php echo $this->getReviewsSummaryHtml($_product, 'short', true);?>
												</div>
												<?php }					 
												if( (int)$this->_getConfig('product_price_display',1) ){ ?>
													<div class="item-price">
														<div class="sale-price">
															<?php echo $this->getPriceHtml($_product,true);?>
														</div>
													</div>
												<?php } ?>
												

												<?php	
												if( (int)$this->_getConfig('product_readmore_display',1) ){?>
												<div class="item-details">
													<a href="<?php echo $_product->link;?>" <?php echo $helper->parseTarget($this->_getConfig('product_links_target'));?> >
														<?php echo $this->_getConfig('product_readmore_text'); ?>
													</a>
												</div>	
												<?php }?>							
											</div>	
											<?php if( $this->_getConfig('theme') == "theme2" ) {
												if( (int)$this->_getConfig('product_title_display',1) && $_product->title !=""){?>
													<div class="item-bg"></div>				
												<?php }
											}?>		
										</div>
									</div>						
								</div>
								</div>
							</div>
						<?php }?>											
						</div>
					</div>
				</div>			
			</div>
			<?php if( $this->_getConfig('cat_sub_display') == 1){?>
				<div class="item-sub-cat">
					<ul>
					<?php foreach( $cat_info as $cat){
						$cat_child = $cat['child'];
						$i = 0;
						foreach( $cat_child as $item ){ 
							$i ++;
							$count_sub = (int)$this->_getConfig('sub_cat_limitation');
							$cur_category = Mage::getModel('catalog/category')->load($item['id']);
							$count = $cur_category->getProductCount();
							if ( $i <= $count_sub ){
						?>
						<li>
							<a href="<?php echo $item['link'];?>" <?php echo $helper->parseTarget($this->_getConfig('link_target', '_self')) ?>>
								<?php echo $item['name'];?>
								<span><?php echo '('.$count.')';?></span>
							</a>
						</li>
					<?php }}}?>
					</ul>

				</div>
			<?php }?>
			<?php foreach( $cat_info as $cat){?>
				<div class="icon-cate">
					<a href="<?php echo $cat['link']; ?>" title="<?php echo $cat['name'];?>">text</a>
				</div>		
			<?php }?>
		</div>		
	</div>
	<?php if( $this->_getConfig('posttext') != '' ) {  ?>
		<div class="post-text"><?php echo $this->_getConfig('posttext'); ?></div>
	<?php } ?>
	
	<script type="text/javascript">
	//<![CDATA[
		$jsmart = jQuery.noConflict();
		$jsmart(document).ready(function($){
		;(function(element){
			var $el = $(element);
			function runSlider(){
				$('.categoryslider',$el).responsiver({
					interval: <?php echo $interval; ?>,
					speed: <?php echo $speed; ?>,
					start: <?php echo $start; ?>,
					step: <?php echo $step; ?>,
					circular: true,
					preload: true,
					fx: 'fade',
					pause: '<?php echo $stop;?>',
					control:{
						prev: '#<?php echo $tag_id;?> .control-button li[class="preview"]',
						next: '#<?php echo $tag_id;?> .control-button li[class="next"]'
					},
					getColumns: function(_element){
						var match = $(_element).attr('class').match(/cols-(\d+)/);
						if (match[1]){
							var column = parseInt(match[1]);
						} else {
							var column = 1;
						}
						if (!column) column = 1;
						return column;
					}          
				});	
			}

			var _timer;
			$(window).load(function(){
				if(_timer) clearTimeout(_timer);
				_timer = setTimeout(function(){
					$el.removeClass('sm-categoryslider-preload');
					$('.sm-categoryslider-loading',$el).remove();
					runSlider();
				},500);
			});

			})('#<?php echo $tag_id;?>')
			
		});
	//]]>
	</script>  	
	
<?php
} else {
	echo $this->__('Has no item to show!');
}?>
 