<?php        
/*------------------------------------------------------------------------
 # SM Categories - Version 1.0
 # Copyright (c) 2009-2011 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.smartaddons.com
-------------------------------------------------------------------------*/
?>
<?php
 $mid = rand().time();
 $smarthelper= Mage::helper('categories/utils');
 $items = $this->getCategory();
 $config = $this->getConfigObject();
 foreach ($config as $key => $value){
	$$key = $value;	
}
 ?>
<?php if($count_items = count($items)):?>

<div id="page-wrap" class="ymcategories">

	<?php if (!empty($config['title'])): ?>
	<div class="block-title block-title-style">
		<span><?php echo $config['title']; ?></span>
	</div>
	<?php endif; ?>
	<!--Intro Text-->
	<?php if($config['pretext']): ?>
	<div style="text-align:left;">
		<?php  echo $config['pretext'];?>
	</div>
	<br/>
	<?php endif;?>
	
	<div id="ytc_tabs<?php echo $mid;?>" class="theme2">
		<div class="box-wrapper">
		<?php			
					
			foreach($items as $key => $item){
			
					$hasChild = count($item['childs'])>0;
							  
				?>
					<div class="item">
					<div class="sub_content">
						<div class="img-category">
							<?php if (($config['category_image_disp'] == 1) && $item['category_thumb']){ ?>
							
								<?php if($config['category_image_linkable'] ==1): ?>		
								<a href="<?php echo $item['category_link']; ?>" <?php echo $smarthelper->getTargetAttr($config['product_links_target']); ?>> 
									<img src="<?php echo $item['category_thumb'] ?>" <?php echo $smarthelper->getTargetAttr($config['product_links_target']); ?> alt="image" />
								</a>                                      									
								<?php else: ?>
								<img src="<?php echo $item['category_thumb']; ?>"/>
								<?php endif;  ?>								
							
							<?php } // show_image? ?>
						</div>
					<?php if ($hasChild): ?>
						<div class="wrap-cate">
							<?php if ($config['category_title_disp'] == 1): ?>
							<div class="parent-title"> 
								<?php if($config['category_title_linkable'] ==1){ ?>		
								<a href="<?php echo $item['category_link'];?>" <?php echo $smarthelper->getTargetAttr($config['product_links_target']); ?>><?php echo $item['category_name'];?></a><br>                                     									
								<?php } else { echo $item['category_name']; }?> 									
							</div>
							<?php endif; ?>
						<?php 
							foreach ($item['childs'] as $child){
						?>
							<div class="sub_category">															
							<?php if ($config['category_sub_title_disp'] == 1){ ?>
								<div class="wrap-title">
									
									<div class="sub_title"> 										
									<?php if($config['category_sub_title_linkable'] ==1) {
										$showNbProducts = (($config['show_total_articles']==1) && $child['products']) ? ' (' . $child['products'] . ')' : '';
									?>		
										<a href="<?php echo $child['category_link'];?>" <?php echo $smarthelper->getTargetAttr($config['product_links_target']); ?>><?php echo $child['category_name'];?></a><br>                                     									
									<?php } else { echo $child['category_name'] ; }?>
									</div>
									
									<?php if ($config['show_total_articles']==1) {?>
									<div class="num_items" style=""><?php echo ' (' . $child['products']. ')';?></div>  									
									<?php }}?>
								</div>									
							</div>
						<?php }?>	
						</div>							
					<?php endif; // if has child ?>
					</div>					
					</div>	
				<?php 	
									
			} // end foreach			
		?>	
		</div> <!-- END Box Wrapper -->
	</div> <!-- END ytc_tabs -->
</div>				
<?php else: ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') . Mage::helper('categories')->__('Please choose a category for Smart Categories.') ?></p>
<?php endif; ?>	
<?php if($config['posttext']): ?>
<br/>
<div style="text-align:left">
	<p><?php  echo $config['posttext'];?></p>
</div>
<?php endif;?>